version: '3.9'

services:
  # Express Server
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    depends_on:
      - postgres
    restart: unless-stopped
    command: ['dumb-init', 'node', 'dist/index.js']

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DATABASE: ${PG_DATABASE}
    env_file:
      - ./.env
    restart: always

volumes:
  db-data:
